### ISSUE TITLE
Permission denied errors when using launch_workbench_job()

### ISSUE THREAD

**Issue by jakeybob** [Public-Health-Scotland/posit-workbench-job-scheduler#14]
**Problem**
Am getting consistent job fails when running `launch_workbench_job()` test script. Fails with exit code = 2 and "Permission denied" shown in the Workbench Jobs interface.

**Fix**
Commenting out the line 
`container = rstudioapi::launcherContainer(image = launcher_info$clusters[[1]]$defaultImage)` from the call to `rstudioapi::launcherSubmitJob()` in `launch_workbench_job()` fixes this for me, but am wondering why this is now the case when it wasn't before? (see `BT_jobTest.R` script in `BT_job_testing` branch for example.)

**Comment by terrymclaughlin** [comment]
@jakeybob 

I ran this with the unedited `launch_workbench_job()` function, and used your `show_job_info()` function, and didn't get any errors:

```
✔ A Workbench Job with id 'S3ViZXJuZXRlczp0ZXN0LXdvcmtiZW5jaC1qb2ItODh4cjU=' and name 'Test Workbench Job' has
  been launched on the cluster 'Kubernetes'.
                user             job_name            submitted         last_updated               status 
          "terrym01" "Test Workbench Job"  "20230320_13:43:41"  "20230320_13:43:41"            "Pending" 
                user             job_name            submitted         last_updated               status 
          "terrym01" "Test Workbench Job"  "20230320_13:43:41"  "20230320_13:43:45"            "Running" 
                user             job_name            submitted         last_updated               status 
          "terrym01" "Test Workbench Job"  "20230320_13:43:41"  "20230320_13:43:45"            "Running" 
                user             job_name            submitted         last_updated               status 
          "terrym01" "Test Workbench Job"  "20230320_13:43:41"  "20230320_13:43:45"            "Running" 
                user             job_name            submitted         last_updated               status 
          "terrym01" "Test Workbench Job"  "20230320_13:43:41"  "20230320_13:43:51"            "Running" 
           exit_code 
                 "0" 
                user             job_name            submitted         last_updated               status 
          "terrym01" "Test Workbench Job"  "20230320_13:43:41"  "20230320_13:43:51"           "Finished" 
           exit_code 
                 "0" 
```

The only thing that I can think that may have caused this is that the default container image was being updated by Scott or Stephen at the time that you tried to run this.

@rmccreath Any chance you could run this and see if it's working for you?  I took the [test](https://github.com/Public-Health-Scotland/posit-workbench-job-scheduler/tree/test) branch and checked out Bob's test script with `git checkout origin/BT_job_testing -- code/BT_job_test.R`  Thanks!

**Comment by daveb-phs** [comment]
I'm getting this bug too. I haven't tried @jakeybob fix yet.

**Comment by daveb-phs** [comment]
@jakeybob

Commenting out the line
container = rstudioapi::launcherContainer(image = launcher_info$clusters[[1]]$defaultImage) from the call to rstudioapi::launcherSubmitJob() in launch_workbench_job()

also fixes the problem for me.

**Comment by jakeybob** [comment]
Just adding this here as a reminder for something else to potentially look into re these issues: 

* workbench jobs launched via the GUI execute as e.g. 

`/bin/bash -c cd ~/working_dir && R --slave --no-save --no-restore -f ~/working_dir/scriptname.R`

so, effectively navigating to the project directory and then calling `R`...

... but when using `launch_workbench_job()` they execute via the command `R` with the appropriate args (`--slave --no-save --no-restore -f /working_dir/scriptname.R`) 

Shouldn't make a difference(?!), but `rstudioapi::launcherSubmitJob()` does allow either `exe = "/bin/bash"` or `command = "R"` to be specified ... and it's interesting that jobs launched via the GUI use the former.

**Comment by jakeybob** [comment]
Also,
 
after scraping some info using `job_info <- rstudioapi::launcherGetJob(job_id)`...

Jobs run using `launch_workbench_job()` as normal have:
* `job_info$container$runAsUserId` and `job_info$container$runAsGroupId` defined as you would expect (ie they match values returned by `id USERNAME` in the terminal)
* `job_info$environment$HOME` set to the correct user home dir

Jobs run with the `container` line commented out of `launch_workbench_job()` have:
* no `runAsUserId` or `runAsGroupId` details
* no `HOME` set

NOTE: can manually add the `runAsUserId` and `runAsGroupId` arguments to `container` definition in `rstudioapi::launcherSubmitJob()` but this causes new errors...

**Comment by jakeybob** [comment]
OK, I still don't get what's happening here but a potentially better fix is the following (@daveb-phs could you try when you have a sec? I've only tested with a v simple script.)

1. comment out the `container` line from the `rstudioapi::launcherSubmitJob()` call in `launch_workbench_job()` as before
2. *add in* the following line `environment = c("HOME" = Sys.getenv("HOME"), "USER" = Sys.getenv("USER"))`

... this should make sure these variables get passed into the environment, so it should know what user it's supposed to be and where HOME is.

note that `Sys.info()[["user"]]` in the job script will still return "root", but `Sys.getenv("USER")` should be the correct username.

So the code block should look like,

```
  # Submit the Workbench Job
  job_id <- rstudioapi::launcherSubmitJob(
    name = ifelse(is.null(job_name), script_file, job_name),
    cluster = launcher_info$clusters[[1]]$name,
    tags = c(job_tag),
    command = "R",
    args = c("--slave", "--no-save", "--no-restore", script_arg),
    workingDirectory = project_path,
    # container = rstudioapi::launcherContainer(image = launcher_info$clusters[[1]]$defaultImage),
    environment = c("HOME" = Sys.getenv("HOME"), 
                    "USER" = Sys.getenv("USER")),
    resourceLimits = job_resource_limits,
    applyConfigSettings = TRUE
  )
```

**Comment by daveb-phs** [comment]
@jakeybob - I've tried this and can confirm that it worked for me. The keyring unlocked fine and the script ran successfully. Excellent! Thanks!

**Comment by jakeybob** [comment]
Excellent, thanks for testing @daveb-phs !

I've put this change into it's own [branch](https://github.com/Public-Health-Scotland/posit-workbench-job-scheduler/tree/14-permission-denied-errors-hotfix), so we can either merge it in or alter it later.

@Theresa2020 @stephcphs you might want to try this as I think/hope these issues might all be the same. Either clone the branch linked above (or manually edit the function as described in the above comments) and see how it goes?

(note: I've not tried scheduling yet, but the scheduling stuff should call the `launch_workbench_job()` function... so if that now works then scheduling should too....)

**Comment by stephcphs** [comment]
@jakeybob This worked for me! Thank you -- will try and schedule something to run tomorrow to double check it's working, but so far so good!

**Comment by jakeybob** [comment]
I've tried some basic scheduling and it seems to be going ok so fingers crossed 🤞🏻

**Comment by Theresa2020** [comment]
Hi @jakeybob can I check what branch to use? Or can I simply use the code you mentioned above? 

 # Submit the Workbench Job
  job_id <- rstudioapi::launcherSubmitJob(
    name = ifelse(is.null(job_name), script_file, job_name),
    cluster = launcher_info$clusters[[1]]$name,
    tags = c(job_tag),
    command = "R",
    args = c("--slave", "--no-save", "--no-restore", script_arg),
    workingDirectory = project_path,
    # container = rstudioapi::launcherContainer(image = launcher_info$clusters[[1]]$defaultImage),
    environment = c("HOME" = Sys.getenv("HOME"), 
                    "USER" = Sys.getenv("USER")),
    resourceLimits = job_resource_limits,
    applyConfigSettings = TRUE
  )

**Comment by jakeybob** [comment]
You can either find that chunk of code and alter it manually (it's at roughly line ~200 in the script `/code/01_Functions_00_launch_workbench_job.R`) but it's probably best/easier to do it by switching to the branch [`14-permission-denied-errors-hotfix`](https://github.com/Public-Health-Scotland/posit-workbench-job-scheduler/tree/14-permission-denied-errors-hotfix), which has that change incorporated.

**Comment by Theresa2020** [comment]
Thanks, I'll try this today and will let you know if this works for me.

**Comment by Theresa2020** [comment]
Hi, I've successfully launched a workbench job using the branch 14-permission-denied-errors-hotfix, so I'll schedule one for tomorrow and see how that goes.

**Comment by Theresa2020** [comment]
I set up my session yesterday with NIGHT at the start of the session name for trying to schedule the automation for this morning. When I have went into Posit this morning, this session has been closed. Is there a reason why this would be, I thought that adding NIGHT was to prevent the forced closure?

**Comment by daveb-phs** [comment]
@Theresa2020 - exactly the same thing has happened to me. I've tried this for the last two nights but each morning I have found the session has disappeared. Last night I logged back in at 8:50pm to check but the session had already closed, so I started a new one just after 9:00pm. I checked at 10:30pm and it was still there - but I couldn't re-open it. It was giving a 403 init error. This morning it has disappeared again.

**Comment by stephcphs** [comment]
@Theresa2020 This also happened to me, twice! I also made sure to put the NIGHT in the session name!

**Comment by daveb-phs** [comment]
My scheduler session just disappeared in front of my eyes right now. Maybe it's a POSIT Workbench issue with sessions disappearing?

**Comment by jakeybob** [comment]
This was a Posit-wide incident (there's a post in the tech queries Teams channel)

**Comment by stephcphs** [comment]
@jakeybob Would this apply to the overnight sessions though?

**Comment by jakeybob** [comment]
Also, for the disappearing NIGHT sessions, could people report via the Posit support request form (if not already) so it gets captured by the data science team?

**Comment by daveb-phs** [comment]
I've submitted a request - ID:264.

**Comment by daveb-phs** [comment]
I started 3 'NIGHT -' sessions last night, one was the scheduling project, one was another random project, one was a session where a project had not been opened. The only one that was still there this morning, but SUSPENDED, was the session where a project hadn't been opened. I'm now wondering if either the opening of a project in a 'NIGHT -' session affects whether it is closed overnight, or if the name of the project is significant. I'm also not sure whether the SUSPENDED status would interfere with scheduling.

Did anyone else manage to schedule something overnight?

**Comment by KatReid** [comment]
There are some issues DaS are looking at. Can I ask if you can check your settings to see if your sessions have: "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"?

**Comment by daveb-phs** [comment]
@KatReid Is that in the launcher diagnostics for the session?

**Comment by KatReid** [comment]
I think so? Sorry I am passing on messages from DaS to get things tried, but havent followed the guidance myself to check yet.

**Comment by daveb-phs** [comment]
@KatReid - no problem. These are the launcher diagnostics for the session that was still there this morning but suspended. I can't access the details of the others but expect them to be the same. I see no mention of the 'safe-to-evict' option.

Session 61babcfc78a31e4085a33 (davidb12) - NIGHT - test no proj
CLUSTER	Kubernetes
STATUS	
FINISHED
EXIT CODE	0
IMAGE	acrdasrstuprd01.azurecr.io/session-prd:rstu-kube
SUBMITTED	30/03/2023, 19:02:30
EXECUTABLE	/usr/lib/rstudio-server/bin/rserver-launcher
ARGUMENTS	--server-user rstudio-server --server-project-sharing 0 --server-shared-storage-path /var/lib/rstudio-server/shared-storage --pam-sessions-enabled 1 --pam-profile rstudio-session --pam-sessions-close 0 --pam-sessions-require-password-prompt 1 --stdin --rserver-address http://172.18.9.37:8787 --rserver-tcp-port 8787 --rserver-verify-ssl-certs 1 --rserver-connection-timeout 10 --session-use-file-storage 1 --log-stderr --create-container-user 1 --container-user-uid 3307 --container-user-gid 1000 --container-user-groups coconnect_data=3500,ICU_extracts=3478,Test-Minimal=3507,isaric_spine=3491,corfiles=214,linkages=3033,pis_corp=3126,vaccine=3443,cohort=3247,acute=136,rldev=30001,UPRN=3434,smr2=113,sls=3054,positwb_high_cpu_128=3528 --container-user-home-dir /mnt/homes/davidb12 --container-user-shell /bin/bash --forward-environment 1
TAGS	61babcfc78a31e4085a3361babcfc78a31e4085a33rstudio-r-sessionrstudio-r-session-name:NIGHT - test no projrstudio-r-session-id:61babcfc78a31e4085a33
LIMITS	cpuCount: 0.25memory: 512

**Comment by KatReid** [comment]
Thanks! Passed that to DaS.

**Comment by daveb-phs** [comment]
@KatReid - I found the details of the scheduler session I set up yesterday. This one closed overnight.

<html>
<body>
<h3 style="box-sizing: border-box; margin: 15px 0px; font-weight: bold; line-height: 1.2; font-size: 20px; padding: 0px; border: 0px; vertical-align: baseline; text-transform: none; color: rgb(48, 48, 48); font-family: Lato, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Session 61bab8f190df57a582bdb (davidb12) - NIGHT - covid scheduler</h3>

CLUSTER | Kubernetes
-- | --
FINISHED
201
acrdasrstuprd01.azurecr.io/session-prd:rstu-kube
30/03/2023, 16:35:44
/usr/lib/rstudio-server/bin/rserver-launcher
--server-user rstudio-server --server-project-sharing 0 --server-shared-storage-path /var/lib/rstudio-server/shared-storage --pam-sessions-enabled 1 --pam-profile rstudio-session --pam-sessions-close 0 --pam-sessions-require-password-prompt 1 --stdin --rserver-address http://172.18.9.37:8787 --rserver-tcp-port 8787 --rserver-verify-ssl-certs 1 --rserver-connection-timeout 10 --session-use-file-storage 1 --log-stderr --create-container-user 1 --container-user-uid 3307 --container-user-gid 1000 --container-user-groups coconnect_data=3500,ICU_extracts=3478,Test-Minimal=3507,isaric_spine=3491,corfiles=214,linkages=3033,pis_corp=3126,vaccine=3443,cohort=3247,acute=136,rldev=30001,UPRN=3434,smr2=113,sls=3054,positwb_high_cpu_128=3528 --container-user-home-dir /mnt/homes/davidb12 --container-user-shell /bin/bash --forward-environment 1
61bab8f190df57a582bdb61bab8f190df57a582bdbrstudio-r-sessionrstudio-r-session-name:NIGHT - covid schedulerrstudio-r-session-id:61bab8f190df57a582bdb
cpuCount: 0.25memory: 512


</body>
</html>

**Comment by Theresa2020** [comment]
@daveb-phs can I ask how you found this information about the session that was closed overnight?

**Comment by daveb-phs** [comment]
@Theresa2020 from the notification that pops up occasionally on the home page saying that there have been x abnormal session exits in the last several hours. It popped up so I clicked on the Details and was able to find the session I started yesterday and get to the launcher diagnostics page.

**Comment by Theresa2020** [comment]
Thanks, I'll keep an eye on that pop-up and I can compare to yours as I had the same issue with my session closing.

**Comment by terrymclaughlin** [comment]
@jakeybob Well done for fixing the problem with the HOME and USER environment variables.  I've got both of these environment variables set somewhere by default, but can't remember where 😂 which is why it was working for me, but not everybody else.
